---
abstract: 'Understand and manipulate IP netmasks'
author:
  - 'Joelle Maslak <jmaslak@antelope.net>'
build_requires:
  Benchmark: '0'
  Test2::V0: '0.000111'
  Test::UseAllModules: '0.17'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Netmask
provides:
  Net::Netmask:
    file: lib/Net/Netmask.pm
    version: '2.0001'
recommends:
  AnyEvent: '7.14'
requires:
  Carp: '0'
  Exporter: '0'
  Math::BigInt: '1.999811'
  POSIX: '0'
  overload: '0'
  perl: 5.006_001
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jmaslak/Net-Netmask/issues
  homepage: http://search.cpan.org/~jmaslak/Net-Netmask/
  repository: git://github.com/jmaslak/Net-Netmask.git
version: '2.0001'
x_contributors:
  - 'Joelle Maslak <jmaslak@antelope.net>'
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
  - 'Adam Herzog <adam@adamherzog.com>'
  - 'Ben Kolera <ben.kolera@gmail.com>'
  - 'bay-max1 <34803732+bay-max1@users.noreply.github.com>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
